main/default/objects/Org_Limit_Schedule_Config__mdt/Org_Limit_Schedule_Config__mdt.object-meta.xml
<CustomObject>
    <description>Stores cron expression for scheduling</description>
    <label>Org Limit Schedule Config</label>
    <pluralLabel>Org Limit Schedule Configs</pluralLabel>
</CustomObject>

main/default/objects/Org_Limit_Schedule_Config__mdt/fields/Cron_Expression__c.field-meta.xml
<CustomField>
    <fullName>Cron_Expression__c</fullName>
    <label>Cron Expression</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Org_Limit_Schedule_Config__mdt/fields/Job_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Job_Identifier__c</fullName>
    <label>Job Identifier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/classes/OrgLimitScheduler.cls
global class OrgLimitScheduler implements Schedulable {

    global void execute(SchedulableContext sc) {
        LimitsForATransactionController.getOrgLimits();
    }

    public static void scheduleJobsDynamically() {
        List<Org_Limit_Schedule_Config__mdt> configs = [
            SELECT Cron_Expression__c, Job_Identifier__c FROM Org_Limit_Schedule_Config__mdt
        ];

        for (Org_Limit_Schedule_Config__mdt config : configs) {
            System.schedule(config.Job_Identifier__c, config.Cron_Expression__c, new OrgLimitScheduler());
        }
    }
}